-- SECURITY: lock down 34 public tables that were RLS-off AND anon-SELECTable
-- (same bug class as the tax_forms leak). Verified 2026-10-02: anon could read real
-- rows incl. User_backup (2732) and MagicLink backup (2635). The frontend anon client
-- reads NONE of these (only parties/guests/experiment_flags/rsvp_checkboxes/slug_aliases/
-- suggestions); backend reads via the service-role/owner role which bypasses RLS, so
-- enabling RLS + revoking anon/authenticated stops the leak without breaking anything.
-- The *_backup_* / *_clobber_backup tables are dead migration leftovers (drop separately).

ALTER TABLE "AIPhoneCall_userId_backup_mushroom_48468" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "AIPhoneCall_userId_backup_mushroom_48468" FROM anon;
REVOKE ALL ON "AIPhoneCall_userId_backup_mushroom_48468" FROM authenticated;
ALTER TABLE "MagicLink_userId_backup_mushroom_48468" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "MagicLink_userId_backup_mushroom_48468" FROM anon;
REVOKE ALL ON "MagicLink_userId_backup_mushroom_48468" FROM authenticated;
ALTER TABLE "User_backup_mushroom_48468" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "User_backup_mushroom_48468" FROM anon;
REVOKE ALL ON "User_backup_mushroom_48468" FROM authenticated;
ALTER TABLE "api_keys_user_id_backup_mushroom_48468" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "api_keys_user_id_backup_mushroom_48468" FROM anon;
REVOKE ALL ON "api_keys_user_id_backup_mushroom_48468" FROM authenticated;
ALTER TABLE "city_telegram_groups" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "city_telegram_groups" FROM anon;
REVOKE ALL ON "city_telegram_groups" FROM authenticated;
ALTER TABLE "event_assistant_log" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "event_assistant_log" FROM anon;
REVOKE ALL ON "event_assistant_log" FROM authenticated;
ALTER TABLE "gpp_agreement_clauses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "gpp_agreement_clauses" FROM anon;
REVOKE ALL ON "gpp_agreement_clauses" FROM authenticated;
ALTER TABLE "graphics_admins" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "graphics_admins" FROM anon;
REVOKE ALL ON "graphics_admins" FROM authenticated;
ALTER TABLE "guest_attestations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "guest_attestations" FROM anon;
REVOKE ALL ON "guest_attestations" FROM authenticated;
ALTER TABLE "guest_scorecard_items" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "guest_scorecard_items" FROM anon;
REVOKE ALL ON "guest_scorecard_items" FROM authenticated;
ALTER TABLE "host_survey_question_sets" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "host_survey_question_sets" FROM anon;
REVOKE ALL ON "host_survey_question_sets" FROM authenticated;
ALTER TABLE "host_survey_questions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "host_survey_questions" FROM anon;
REVOKE ALL ON "host_survey_questions" FROM authenticated;
ALTER TABLE "host_survey_responses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "host_survey_responses" FROM anon;
REVOKE ALL ON "host_survey_responses" FROM authenticated;
ALTER TABLE "image_authenticity_checks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "image_authenticity_checks" FROM anon;
REVOKE ALL ON "image_authenticity_checks" FROM authenticated;
ALTER TABLE "invoice_counters" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "invoice_counters" FROM anon;
REVOKE ALL ON "invoice_counters" FROM authenticated;
ALTER TABLE "mercury_wire_matches" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "mercury_wire_matches" FROM anon;
REVOKE ALL ON "mercury_wire_matches" FROM authenticated;
ALTER TABLE "parties_user_id_backup_mushroom_48468" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "parties_user_id_backup_mushroom_48468" FROM anon;
REVOKE ALL ON "parties_user_id_backup_mushroom_48468" FROM authenticated;
ALTER TABLE "partner_ai_share_tokens" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "partner_ai_share_tokens" FROM anon;
REVOKE ALL ON "partner_ai_share_tokens" FROM authenticated;
ALTER TABLE "partner_event_notes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "partner_event_notes" FROM anon;
REVOKE ALL ON "partner_event_notes" FROM authenticated;
ALTER TABLE "party_payment_opt_ins" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "party_payment_opt_ins" FROM anon;
REVOKE ALL ON "party_payment_opt_ins" FROM authenticated;
ALTER TABLE "party_telegram_contributors" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "party_telegram_contributors" FROM anon;
REVOKE ALL ON "party_telegram_contributors" FROM authenticated;
ALTER TABLE "party_telegram_hosts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "party_telegram_hosts" FROM anon;
REVOKE ALL ON "party_telegram_hosts" FROM authenticated;
ALTER TABLE "payout_document_votes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "payout_document_votes" FROM anon;
REVOKE ALL ON "payout_document_votes" FROM authenticated;
ALTER TABLE "payouts_host_user_id_backup_mushroom_48468" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "payouts_host_user_id_backup_mushroom_48468" FROM anon;
REVOKE ALL ON "payouts_host_user_id_backup_mushroom_48468" FROM authenticated;
ALTER TABLE "photo_votes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "photo_votes" FROM anon;
REVOKE ALL ON "photo_votes" FROM authenticated;
ALTER TABLE "photos_created_at_clobber_backup" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "photos_created_at_clobber_backup" FROM anon;
REVOKE ALL ON "photos_created_at_clobber_backup" FROM authenticated;
ALTER TABLE "reimbursement_cap_appeals" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "reimbursement_cap_appeals" FROM anon;
REVOKE ALL ON "reimbursement_cap_appeals" FROM authenticated;
ALTER TABLE "reimbursement_cap_audit" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "reimbursement_cap_audit" FROM anon;
REVOKE ALL ON "reimbursement_cap_audit" FROM authenticated;
ALTER TABLE "rsvp_funnel_events" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "rsvp_funnel_events" FROM anon;
REVOKE ALL ON "rsvp_funnel_events" FROM authenticated;
ALTER TABLE "saved_filter_views" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "saved_filter_views" FROM anon;
REVOKE ALL ON "saved_filter_views" FROM authenticated;
ALTER TABLE "side_agreement_clauses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "side_agreement_clauses" FROM anon;
REVOKE ALL ON "side_agreement_clauses" FROM authenticated;
ALTER TABLE "survey_question_sets" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "survey_question_sets" FROM anon;
REVOKE ALL ON "survey_question_sets" FROM authenticated;
ALTER TABLE "survey_questions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "survey_questions" FROM anon;
REVOKE ALL ON "survey_questions" FROM authenticated;
ALTER TABLE "telegram_broadcast_log" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "telegram_broadcast_log" FROM anon;
REVOKE ALL ON "telegram_broadcast_log" FROM authenticated;
