import type { FormatConfig } from '../types';

export const POSTER_CONFIG: FormatConfig = {
  id: 'poster',
  label: 'Event Poster',
  templatePath: '/gpp-poster-2026-template.png',
  fullResUrl: 'https://znpiwdvvsqaxuskpfleo.supabase.co/storage/v1/object/public/templates/gpp-poster-2026-fullres.png',
  canvasWidth: 1080,
  canvasHeight: 1440,
  fullResWidth: 5400,
  fullResHeight: 7200,
  previewMaxWidth: 400,
  textFields: [
    {
      key: 'city',
      label: 'City',
      defaultX: 50,
      defaultY: 800,
      boxWidth: 700,
      boxHeight: 72,
      color: '#FE332C',
      fontFamily: '"Hub 191 Display", "Hub 191", "Comic Sans MS", cursive',
      maxFontSize: 64,
    },
    {
      key: 'time',
      label: 'Time',
      defaultX: 50,
      defaultY: 880,
      boxWidth: 700,
      boxHeight: 60,
      color: '#FFFFFF',
      fontFamily: '"Hub 191", "Comic Sans MS", "Comic Sans", cursive',
      maxFontSize: 55,
    },
    {
      key: 'venue',
      label: 'Venue',
      defaultX: 50,
      defaultY: 950,
      boxWidth: 700,
      boxHeight: 110,
      color: '#0497C1',
      fontFamily: '"Hub 191", "Comic Sans MS", "Comic Sans", cursive',
      maxFontSize: 46,
    },
  ],
  sponsorBox: {
    defaultX: 27,
    defaultY: 1080,
    width: 1026,
    height: 90,
  },
  dbImageField: 'poster_image_url',
  dbTimestampField: 'poster_generated_at',
  storageKey: (partyId: string) => `poster-${partyId}`,
};
