import type { FormatConfig } from '../types';

export const ROLLUP_CONFIG: FormatConfig = {
  id: 'rollup',
  label: 'Roll-Up Banner',
  templatePath: '/gpp-rollup-2026-template.png',
  fullResUrl: 'https://znpiwdvvsqaxuskpfleo.supabase.co/storage/v1/object/public/templates/gpp-rollup-2026-fullres.png',
  canvasWidth: 1080,
  canvasHeight: 2940,
  fullResWidth: 10061,
  fullResHeight: 27392,
  previewMaxWidth: 350,
  previewMaxHeight: 500,
  textFields: [
    {
      key: 'city',
      label: 'City',
      defaultX: 80,
      defaultY: 2200,
      boxWidth: 920,
      boxHeight: 100,
      color: '#FE332C',
      fontFamily: '"Hub 191 Display", "Hub 191", "Comic Sans MS", cursive',
      maxFontSize: 72,
    },
    {
      key: 'time',
      label: 'Time',
      defaultX: 80,
      defaultY: 2320,
      boxWidth: 920,
      boxHeight: 80,
      color: '#FFFFFF',
      fontFamily: '"Hub 191", "Comic Sans MS", "Comic Sans", cursive',
      maxFontSize: 60,
      hidden: true,
    },
    {
      key: 'venue',
      label: 'Venue',
      defaultX: 80,
      defaultY: 2420,
      boxWidth: 920,
      boxHeight: 150,
      color: '#0497C1',
      fontFamily: '"Hub 191", "Comic Sans MS", "Comic Sans", cursive',
      maxFontSize: 50,
      hidden: true,
    },
  ],
  sponsorBox: {
    defaultX: 60,
    defaultY: 2600,
    width: 960,
    height: 300,
  },
  dbImageField: 'rollup_image_url',
  dbTimestampField: 'rollup_generated_at',
  storageKey: (partyId: string) => `rollup-${partyId}`,
};
