/**
 * Country long name -> ISO 3166-1 alpha-2 code.
 *
 * Source of long names: Google Places `country.long_name` (used by
 * LocationAutocomplete when an event is created/edited). Includes a few
 * common aliases the wild data has produced ("USA", "UK", etc.).
 */
export const NAME_TO_CODE: Record<string, string> = {
  'Afghanistan': 'AF',
  'Åland Islands': 'AX',
  'Aland Islands': 'AX',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'American Samoa': 'AS',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Anguilla': 'AI',
  'Antarctica': 'AQ',
  'Antigua and Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Aruba': 'AW',
  'Australia': 'AU',
  'Austria': 'AT',
  'Österreich': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'The Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'België': 'BE',
  'Belgique': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bermuda': 'BM',
  'Bhutan': 'BT',
  'Bolivia': 'BO',
  'Bosnia and Herzegovina': 'BA',
  'Botswana': 'BW',
  'Bouvet Island': 'BV',
  'Brazil': 'BR',
  'Brasil': 'BR',
  'British Indian Ocean Territory': 'IO',
  'British Virgin Islands': 'VG',
  'Brunei': 'BN',
  'Brunei Darussalam': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cabo Verde': 'CV',
  'Cape Verde': 'CV',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Caribbean Netherlands': 'BQ',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  'China': 'CN',
  "People's Republic of China": 'CN',
  '中国': 'CN',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo': 'CG',
  'Republic of the Congo': 'CG',
  'Congo - Brazzaville': 'CG',
  'Congo - Kinshasa': 'CD',
  'Democratic Republic of the Congo': 'CD',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  "Côte d'Ivoire": 'CI',
  "Cote d'Ivoire": 'CI',
  'Ivory Coast': 'CI',
  'Croatia': 'HR',
  'Hrvatska': 'HR',
  'Cuba': 'CU',
  'Curaçao': 'CW',
  'Curacao': 'CW',
  'Cyprus': 'CY',
  'Czechia': 'CZ',
  'Czech Republic': 'CZ',
  'Česko': 'CZ',
  'Denmark': 'DK',
  'Danmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Ecuador': 'EC',
  'Egypt': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Eswatini': 'SZ',
  'Swaziland': 'SZ',
  'Ethiopia': 'ET',
  'Falkland Islands': 'FK',
  'Falkland Islands (Malvinas)': 'FK',
  'Faroe Islands': 'FO',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'Suomi': 'FI',
  'France': 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  'Gabon': 'GA',
  'Gambia': 'GM',
  'The Gambia': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Deutschland': 'DE',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greece': 'GR',
  'Ελλάδα': 'GR',
  'Greenland': 'GL',
  'Grenada': 'GD',
  'Guadeloupe': 'GP',
  'Guam': 'GU',
  'Guatemala': 'GT',
  'Guernsey': 'GG',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Heard Island and McDonald Islands': 'HM',
  'Honduras': 'HN',
  'Hong Kong': 'HK',
  'Hungary': 'HU',
  'Magyar': 'HU',
  'Magyarország': 'HU',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran': 'IR',
  'Iran (Islamic Republic of)': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Isle of Man': 'IM',
  'Israel': 'IL',
  'Italy': 'IT',
  'Italia': 'IT',
  'Jamaica': 'JM',
  'Japan': 'JP',
  '日本': 'JP',
  'Jersey': 'JE',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  'Kosovo': 'XK',
  'Kuwait': 'KW',
  'Kyrgyzstan': 'KG',
  'Laos': 'LA',
  "Lao People's Democratic Republic": 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Macao': 'MO',
  'Macau': 'MO',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Martinique': 'MQ',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mayotte': 'YT',
  'Mexico': 'MX',
  'México': 'MX',
  'Micronesia': 'FM',
  'Federated States of Micronesia': 'FM',
  'Moldova': 'MD',
  'Republic of Moldova': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Montserrat': 'MS',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Myanmar': 'MM',
  'Myanmar (Burma)': 'MM',
  'Burma': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'The Netherlands': 'NL',
  'Nederland': 'NL',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'Niue': 'NU',
  'Norfolk Island': 'NF',
  'North Korea': 'KP',
  "Democratic People's Republic of Korea": 'KP',
  'North Macedonia': 'MK',
  'Macedonia': 'MK',
  'Northern Mariana Islands': 'MP',
  'Norway': 'NO',
  'Norge': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Palestine': 'PS',
  'State of Palestine': 'PS',
  'Palestinian Territories': 'PS',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Perú': 'PE',
  'Philippines': 'PH',
  'Pitcairn Islands': 'PN',
  'Poland': 'PL',
  'Polska': 'PL',
  'Portugal': 'PT',
  'Puerto Rico': 'PR',
  'Qatar': 'QA',
  'Réunion': 'RE',
  'Reunion': 'RE',
  'Romania': 'RO',
  'România': 'RO',
  'Russia': 'RU',
  'Russian Federation': 'RU',
  'Россия': 'RU',
  'Rwanda': 'RW',
  'Saint Barthélemy': 'BL',
  'St. Barthélemy': 'BL',
  'Saint Helena': 'SH',
  'St. Helena': 'SH',
  'Saint Kitts and Nevis': 'KN',
  'St. Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'St. Lucia': 'LC',
  'Saint Martin': 'MF',
  'St. Martin': 'MF',
  'Saint Pierre and Miquelon': 'PM',
  'St. Pierre and Miquelon': 'PM',
  'Saint Vincent and the Grenadines': 'VC',
  'St. Vincent and the Grenadines': 'VC',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'São Tomé and Príncipe': 'ST',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Sint Maarten': 'SX',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Georgia and the South Sandwich Islands': 'GS',
  'South Korea': 'KR',
  'Korea, Republic of': 'KR',
  'Republic of Korea': 'KR',
  'Korea': 'KR',
  '한국': 'KR',
  '대한민국': 'KR',
  'South Sudan': 'SS',
  'Spain': 'ES',
  'España': 'ES',
  'Sri Lanka': 'LK',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Svalbard and Jan Mayen': 'SJ',
  'Sweden': 'SE',
  'Sverige': 'SE',
  'Switzerland': 'CH',
  'Schweiz': 'CH',
  'Suisse': 'CH',
  'Syria': 'SY',
  'Syrian Arab Republic': 'SY',
  'Taiwan': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania': 'TZ',
  'United Republic of Tanzania': 'TZ',
  'Thailand': 'TH',
  'Timor-Leste': 'TL',
  'East Timor': 'TL',
  'Togo': 'TG',
  'Tokelau': 'TK',
  'Tonga': 'TO',
  'Trinidad and Tobago': 'TT',
  'Tunisia': 'TN',
  'Turkey': 'TR',
  'Türkiye': 'TR',
  'Turkiye': 'TR',
  'Turkmenistan': 'TM',
  'Turks and Caicos Islands': 'TC',
  'Tuvalu': 'TV',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'Україна': 'UA',
  'United Arab Emirates': 'AE',
  'UAE': 'AE',
  'United Kingdom': 'GB',
  'UK': 'GB',
  'Great Britain': 'GB',
  'Britain': 'GB',
  'England': 'GB',
  'Scotland': 'GB',
  'Wales': 'GB',
  'Northern Ireland': 'GB',
  'United States': 'US',
  'United States of America': 'US',
  'USA': 'US',
  'U.S.A.': 'US',
  'U.S.': 'US',
  'America': 'US',
  'United States Minor Outlying Islands': 'UM',
  'U.S. Virgin Islands': 'VI',
  'US Virgin Islands': 'VI',
  'Virgin Islands, U.S.': 'VI',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Vatican City': 'VA',
  'Holy See': 'VA',
  'Holy See (Vatican City State)': 'VA',
  'Venezuela': 'VE',
  'Vietnam': 'VN',
  'Viet Nam': 'VN',
  'Wallis and Futuna': 'WF',
  'Western Sahara': 'EH',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
};

const MAP_EMOJI_FALLBACK = '\u{1F5FA}\u{FE0F}';

/**
 * Convert a country long name (as stored in `parties.country`) to a
 * flag emoji. Falls back to the world map 🗺️ for null/empty/unknown
 * input so behavior never regresses below the prior map-emoji default.
 */
export function countryNameToFlag(name: string | null | undefined): string {
  if (!name) return MAP_EMOJI_FALLBACK;
  const code = NAME_TO_CODE[name.trim()];
  if (!code || code.length !== 2) return MAP_EMOJI_FALLBACK;
  const upper = code.toUpperCase();
  return String.fromCodePoint(
    upper.charCodeAt(0) + 127397,
    upper.charCodeAt(1) + 127397,
  );
}

/**
 * Convert a country long name (as stored in `parties.country`) to its
 * ISO-3166-1 alpha-2 code. Returns null when the name is unknown.
 * Used by callers that need the code itself (e.g. building a flag-SVG URL).
 */
export function countryNameToAlpha2(name: string | null | undefined): string | null {
  if (!name) return null;
  const code = NAME_TO_CODE[name.trim()];
  if (!code || code.length !== 2) return null;
  return code.toLowerCase(); // lowercase is what circle-flags filenames use
}

// sicilian-58129: reverse lookup — every long-name variant we know for a given
// alpha-2 code. Used by /photos filter to expand "ES" -> ["Spain","España"]
// before sending the raw country list to the backend.
let _codeToNames: Map<string, string[]> | null = null;
function buildCodeToNames(): Map<string, string[]> {
  if (_codeToNames) return _codeToNames;
  const m = new Map<string, string[]>();
  for (const [name, code] of Object.entries(NAME_TO_CODE)) {
    if (!code || code.length !== 2) continue;
    const key = code.toUpperCase();
    const arr = m.get(key) ?? [];
    arr.push(name);
    m.set(key, arr);
  }
  _codeToNames = m;
  return m;
}

export function alpha2ToCountryNames(alpha2: string): string[] {
  if (!alpha2) return [];
  return buildCodeToNames().get(alpha2.toUpperCase()) ?? [];
}

// Preferred canonical display name per alpha-2. Picks the English name where
// available, otherwise the first variant we know.
const PREFERRED_NAME_BY_CODE: Record<string, string> = {
  ES: 'Spain', CN: 'China', MX: 'Mexico', US: 'United States', GB: 'United Kingdom',
  DE: 'Germany', FR: 'France', IT: 'Italy', JP: 'Japan', KR: 'South Korea',
  BR: 'Brazil', AT: 'Austria', BE: 'Belgium', NL: 'Netherlands', PT: 'Portugal',
  CH: 'Switzerland', SE: 'Sweden', NO: 'Norway', DK: 'Denmark', FI: 'Finland',
  PL: 'Poland', CZ: 'Czechia', GR: 'Greece', TR: 'Turkey', RU: 'Russia',
  IN: 'India', CA: 'Canada', AU: 'Australia', NZ: 'New Zealand', ZA: 'South Africa',
  AR: 'Argentina', CL: 'Chile', CO: 'Colombia', PE: 'Peru', VE: 'Venezuela',
  EG: 'Egypt', NG: 'Nigeria', KE: 'Kenya', GH: 'Ghana', MA: 'Morocco',
  TH: 'Thailand', VN: 'Vietnam', PH: 'Philippines', ID: 'Indonesia', MY: 'Malaysia',
  SG: 'Singapore', TW: 'Taiwan', HK: 'Hong Kong', AE: 'United Arab Emirates',
  IL: 'Israel', SA: 'Saudi Arabia', IR: 'Iran', PK: 'Pakistan', BD: 'Bangladesh',
};

export function alpha2ToCanonicalName(alpha2: string): string {
  if (!alpha2) return '';
  const code = alpha2.toUpperCase();
  if (PREFERRED_NAME_BY_CODE[code]) return PREFERRED_NAME_BY_CODE[code];
  const names = buildCodeToNames().get(code);
  return names && names.length > 0 ? names[0] : code;
}
