ALTER TABLE parties ADD COLUMN IF NOT EXISTS poster_image_url TEXT NULL;
ALTER TABLE parties ADD COLUMN IF NOT EXISTS poster_generated_at TIMESTAMPTZ NULL;
ALTER TABLE parties ADD COLUMN IF NOT EXISTS rollup_image_url TEXT NULL;
ALTER TABLE parties ADD COLUMN IF NOT EXISTS rollup_generated_at TIMESTAMPTZ NULL;
